/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.UsuarioDAO;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.proteanit.sql.DbUtils;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Welington
 */
public class ConsultarUsuarioUI extends javax.swing.JFrame {

    UsuarioDAO usuarioDao = new UsuarioDAO();
    ResultSet dados = null;
    Vector<Vector<String>> listaUsuarios = new Vector<Vector<String>>();     
    
    DefaultTableModel modelo = new DefaultTableModel();
    /**
     * Creates new form ConsultarUsuarioUI
     */
    public ConsultarUsuarioUI() {
        initComponents();
       /* cab.add("nome");
        cab.add("apelido");
        cab.add("cpf");
        cab.add("telefone");
        cab.add("senha");
        cab.add("rua");
        cab.add("numero");
        cab.add("complemento");
        cab.add("bairro");
        cab.add("cidade");
        cab.add("cep");*/
    }
    //DefaultTableModel model = new DefaultTableModel(null, new String[]{"Depth","Temperature","D.O."});
                

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        entradaBuscaNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Consultar Usuário");

        jLabel2.setText("Busca por Nome:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        entradaBuscaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaBuscaNomeActionPerformed(evt);
            }
        });
        entradaBuscaNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                entradaBuscaNomeKeyTyped(evt);
            }
        });

        jLabel3.setText("Lista com todos");

        jTable1.setModel(modelo);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entradaBuscaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(143, 143, 143))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(entradaBuscaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addGap(95, 95, 95))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entradaBuscaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaBuscaNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaBuscaNomeActionPerformed

    private void entradaBuscaNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_entradaBuscaNomeKeyTyped
        // TODO add your handling code here:
        //jTable1.setModel(modelo);
        //System.out.println(""+usuarioDao.consultaNome(entradaBuscaNome.getText()));
        ResultSet r = usuarioDao.consultaNome(entradaBuscaNome.getText());
        if(r==null){
        jTable1.setModel(modelo);
        }
        if(r!=null){
            
            dados=r;
            //TableModel modelo=DbUtils.resultSetToTableModel(r);
            //jTable1.setModel(modelo);
        try {
            ResultSetMetaData metaData = r.getMetaData();
            int contadorColuna = metaData.getColumnCount();
            Vector<String> nomeColunas = new Vector<String>();    
            for(int i=1;i<=contadorColuna;i++){
                nomeColunas.add(metaData.getColumnName(i));
            }
            Object[] Colunas = {nomeColunas};
            while (r.next()){
                System.out.println("i");
                System.out.println(" "+r.getString("nome"));
                Vector<String> usuario = new Vector <>();
                usuario.add(r.getString("nome"));
                usuario.add(r.getString("apelido"));
                usuario.add(r.getString("cpf"));
                usuario.add(r.getString("telefone"));
                usuario.add(r.getString("senha"));
                usuario.add(r.getString("rua"));
                usuario.add(r.getString("numero"));
                usuario.add(r.getString("complemento"));
                usuario.add(r.getString("bairro"));
                usuario.add(r.getString("cidade"));
                usuario.add(r.getString("cep"));
                listaUsuarios.add(usuario);
                Object[][] linha = {{r.getString("nome"),r.getString("apelido"),r.getString("cpf"),r.getString("telefone"),
                    r.getString("rua"),r.getString("numero"),r.getString("complemento"),r.getString("bairro"),r.getString("cidade"),r.getString("cep")}};
                //modelo.setDataVector(listaUsuarios, nomeColunas);
                DefaultTableModel modelo2 = new DefaultTableModel(linha,Colunas);
                jTable1.setModel(modelo2);
                
            }
//            entradaBuscaNome.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(ConsultarUsuarioUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_entradaBuscaNomeKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarUsuarioUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField entradaBuscaNome;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
